//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UsersAndRolesDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Property
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Property()
        {
            this.PropertyImages = new HashSet<PropertyImage>();
            this.Reservations = new HashSet<Reservation>();
        }
    
        public int Id { get; set; }
        public string UserId { get; set; }
        public string summary { get; set; }
        public string propertyType { get; set; }
        public Nullable<int> numBedrooms { get; set; }
        public Nullable<int> numWashrooms { get; set; }
        public Nullable<int> kitchen { get; set; }
        public Nullable<decimal> baseRate { get; set; }
        public string address { get; set; }
        public string builtYear { get; set; }
        public string smokingAllowed { get; set; }
        public string maxNumberGuests { get; set; }
        public Nullable<System.DateTime> availableDates { get; set; }
        public string dimensions { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyImage> PropertyImages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reservation> Reservations { get; set; }
    }
}
